project:
  type: book

book:
  title: "ds6400_portfolio"
  author: "Samia Mahmood"
  date: "8/27/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Performance Measures"
      chapters:
        - simulation-study.qmd
        - simulation-study-bates-2023.qmd
    - part: "Visualizing Models"
      chapters:
        - visualizing_model_molnar_2022.qmd
    - summary.qmd
    - references.qmd
    - part: "Appendix"
      chapters:
        - bivariate_norm_dist.qmd
        - cross_validation.qmd
        - boostrapping.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand



