<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Ordinal Regression – ds6400_portfolio</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./summary.html" rel="next">
<link href="./visualizing_model_molnar_2022.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-631496449bf32ff9b0bb69a6bfd9195d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./ordinal_regression.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Ordinal Regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">ds6400_portfolio</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DS-6400: Advanced Machine Learning I Portfolio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Performance Measures</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./simulation-study.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Simulation Study Efron 1983</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./simulation-study-bates-2023.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Simulation Study Bates 2023</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Visualizing Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./visualizing_model_molnar_2022.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Partial Dependence Plot (PDP)</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ordinal_regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Ordinal Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Summary</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendix</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bivariate_norm_dist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Class-conditional bivariate normal distribution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cross_validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Cross Validation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./boostrapping.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Bootstrapping</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#motivation" id="toc-motivation" class="nav-link active" data-scroll-target="#motivation"><span class="header-section-number">5.1</span> Motivation:</a></li>
  <li><a href="#what-does-ordinal-mean" id="toc-what-does-ordinal-mean" class="nav-link" data-scroll-target="#what-does-ordinal-mean"><span class="header-section-number">5.2</span> What does Ordinal Mean?</a></li>
  <li><a href="#what-problem-is-the-paper-addressing" id="toc-what-problem-is-the-paper-addressing" class="nav-link" data-scroll-target="#what-problem-is-the-paper-addressing"><span class="header-section-number">5.3</span> What Problem is the Paper Addressing</a></li>
  <li><a href="#cumulative-probability-model-cpm" id="toc-cumulative-probability-model-cpm" class="nav-link" data-scroll-target="#cumulative-probability-model-cpm"><span class="header-section-number">5.4</span> Cumulative Probability Model (CPM)</a>
  <ul class="collapse">
  <li><a href="#mathematically-deriving-the-cpm" id="toc-mathematically-deriving-the-cpm" class="nav-link" data-scroll-target="#mathematically-deriving-the-cpm"><span class="header-section-number">5.4.1</span> Mathematically Deriving the CPM:</a></li>
  <li><a href="#relation-between-the-cpm-and-being-semiparametric" id="toc-relation-between-the-cpm-and-being-semiparametric" class="nav-link" data-scroll-target="#relation-between-the-cpm-and-being-semiparametric"><span class="header-section-number">5.4.2</span> Relation Between the CPM and Being Semiparametric:</a></li>
  <li><a href="#choosing-the-link-function" id="toc-choosing-the-link-function" class="nav-link" data-scroll-target="#choosing-the-link-function"><span class="header-section-number">5.4.3</span> Choosing the Link Function:</a></li>
  </ul></li>
  <li><a href="#model-demonstration-in-code---single-dataset-evaluation-of-the-cpm" id="toc-model-demonstration-in-code---single-dataset-evaluation-of-the-cpm" class="nav-link" data-scroll-target="#model-demonstration-in-code---single-dataset-evaluation-of-the-cpm"><span class="header-section-number">5.5</span> Model Demonstration in Code - Single Dataset Evaluation of the CPM:</a>
  <ul class="collapse">
  <li><a href="#step-1-the-data-generating-process" id="toc-step-1-the-data-generating-process" class="nav-link" data-scroll-target="#step-1-the-data-generating-process"><span class="header-section-number">5.5.1</span> Step 1: The Data-Generating Process</a></li>
  <li><a href="#step-2-traintest-split" id="toc-step-2-traintest-split" class="nav-link" data-scroll-target="#step-2-traintest-split"><span class="header-section-number">5.5.2</span> Step 2: Train/Test Split</a></li>
  <li><a href="#step-3-fit-the-cpm-on-the-training-set" id="toc-step-3-fit-the-cpm-on-the-training-set" class="nav-link" data-scroll-target="#step-3-fit-the-cpm-on-the-training-set"><span class="header-section-number">5.5.3</span> Step 3: Fit the CPM on the Training Set</a></li>
  <li><a href="#step-4-prediction-rules-from-the-fitted-cdf" id="toc-step-4-prediction-rules-from-the-fitted-cdf" class="nav-link" data-scroll-target="#step-4-prediction-rules-from-the-fitted-cdf"><span class="header-section-number">5.5.4</span> Step 4: Prediction Rules from the Fitted CDF</a></li>
  <li><a href="#step-5-out-of-sample-performance" id="toc-step-5-out-of-sample-performance" class="nav-link" data-scroll-target="#step-5-out-of-sample-performance"><span class="header-section-number">5.5.5</span> Step 5: Out-of-Sample Performance</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Ordinal Regression</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<ul>
<li><strong>Article Titie:</strong> Modeling Continuous Response Variables Using Ordinal Regression</li>
<li><strong>Author:</strong> Qi Liu, Bryan E. Shepherd, Chun Li, Frank E. Harrell Jr.</li>
</ul>
<p>Modeling Continuous Response Variables Using Ordinal Regression <span class="citation" data-cites="liu2017">(<a href="references.html#ref-liu2017" role="doc-biblioref">Liu et al. 2017</a>)</span> introduces the concept of Ordinal Regression.</p>
<section id="motivation" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="motivation"><span class="header-section-number">5.1</span> Motivation:</h2>
<ul>
<li>A <strong>continuous variable/measurement</strong> is also an <strong>ordered variable/measurement.</strong></li>
<li>Instead of trying to guess the exact shape of the outcome distribution or the exact transformation needed like in linear regression, we can model the probability that the <strong>continuous outcome is below any particular value.</strong></li>
<li>Therefore, ordinal regression does not assume a shape for the outcvome distribution.</li>
</ul>
</section>
<section id="what-does-ordinal-mean" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="what-does-ordinal-mean"><span class="header-section-number">5.2</span> What does Ordinal Mean?</h2>
<ul>
<li><strong>Ordinal</strong> - means that there is an order to the possible outcomes.</li>
<li>Consider an example where our outcome is to determine health improvement in a patient:
<ul>
<li>For a categorical variable where values are ordered, <strong>(Ordinal Categorical Discrete Variable)</strong>:
<ul>
<li>For example: Poor &lt; Fair &lt; Good &lt; Excellent</li>
</ul></li>
<li>One can intuitively understand that Poor &lt; Fair.</li>
<li>However, we don’t necessarily know that the difference between Poor and Fair is numerically equal to the difference between Good and Excellent.</li>
<li>The jump from Poor to Fair might not represent the same amount of health improvement as Good to Excellent.</li>
</ul></li>
<li>Consider an example where our outcome is to determine the weight in a patient:
<ul>
<li>For a continuous numerical variable, values are ordered, <strong>(Ordinal Numerical Continuous Variable)</strong>, but they also have numerical distances.
<ul>
<li>For example: 120 &lt; 135 &lt; 190 &lt; 230 (in lb)</li>
</ul></li>
<li>The differences or distances between each value have a numerical meaning</li>
</ul></li>
<li><strong>The main insight of the paper is Ordinal Regression uses ordering without assuming anything about the shape of the outcome distribution</strong>.</li>
<li><strong>Ordinal regression allows us to provide meaning to ordered outcomes after a transformation has been performed</strong>.</li>
</ul>
</section>
<section id="what-problem-is-the-paper-addressing" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="what-problem-is-the-paper-addressing"><span class="header-section-number">5.3</span> What Problem is the Paper Addressing</h2>
<ul>
<li>Suppose we want to predict a continuous numerical outcome <span class="math inline">\(Y_i\)</span> = blood pressure, and predictor variables <span class="math inline">\(X_i\)</span>, such as age, height, gender, etc.</li>
<li>One could use <strong>Linear Regression</strong> to predict <span class="math inline">\(Y_i\)</span> = blood pressure: <span class="math display">\[ Y_i = \beta_0+\beta_1X_{i1}+\beta_2X_{i2}+\cdots+\epsilon_i. \]</span></li>
<li><strong>The problem: Linear regression makes assumptions about the distribution of Y</strong>
<ul>
<li>Assumption #1: Linearity of the conditional mean - The average value of Y, given X, is a linear function of <span class="math inline">\(X_i\)</span>. <span class="math display">\[ E(Y_i|X_i) = \beta_0+\beta_1X_{i1} \]</span></li>
<li>Assumption #2: Homoscedasticity - The amount of variability around the regression line is assumed to be roughly constant across values of <span class="math inline">\(X_i\)</span> where <span class="math inline">\(σ^2\)</span> does not depend on <span class="math inline">\(X_i\)</span>. <span class="math display">\[ Var(\epsilon_i∣X_i)=σ^2​ \]</span></li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/homoscedasticty.jpg" class="img-fluid figure-img"></p>
<figcaption>Figure 1: Diagram of Homoscedasticity vs.&nbsp;Heteroscedasticty.</figcaption>
</figure>
</div>
<ul>
<li>Assumption #3: Errors are independent <span class="math display">\[ \epsilon_1, \epsilon_2 ,  \epsilon_3, \cdots, independent \]</span></li>
<li>Assumption #4: The errors have mean zero - Model does not systematically overpredict or underpredict the target variable <span class="math display">\[ E(Y_i|X_i) = 0 \]</span></li>
<li><strong>Assumption #5: Appropriate transformation choice for Y</strong>
<ul>
<li>Assume <span class="math inline">\(Y_i\)</span> is heavily-rigth skewed. One might take the log(<span class="math inline">\(Y_i\)</span>) such that: <span class="math display">\[ log(Y_i) = \beta_0+\beta_1X_{i1}+\beta_2X_{i2}+\cdots+\epsilon_i. \]</span></li>
<li>But how do we know that logarithm is the right transformation? What about <span class="math inline">\(Y_i^2\)</span>, <span class="math inline">\(\sqrt{Y_i}\)</span>, etc. <strong>The correct transformation is often unknown.</strong></li>
</ul></li>
</ul></li>
<li><strong>To avoid arbitrarily picking a linear transformation</strong>, the paper says to use the <strong>Cumulative probability model (CPM)</strong>.</li>
</ul>
</section>
<section id="cumulative-probability-model-cpm" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="cumulative-probability-model-cpm"><span class="header-section-number">5.4</span> Cumulative Probability Model (CPM)</h2>
<p>Also called the <strong>Cumulative Link Model</strong></p>
<p>The <strong>cumulative probability model (CPM)</strong> is a type of <strong>Ordinal Regression Model</strong>. Instead of modeling the outcome <span class="math inline">\(Y\)</span> (a continuous ordinal variable) directly, it models the probability that <span class="math inline">\(Y\)</span> is at or below a cutoff <span class="math inline">\(y\)</span> (which is a specific value we specify) given predictors <span class="math inline">\(X\)</span>. <span class="math display">\[ P(Y≤y∣X) \]</span> The CPM can be computed every every possible cutoff value <span class="math inline">\(y\)</span> which is the <strong>conditional cumulative distribution function (CDF)</strong> of an outcome given a set of covariates. Therefore, it models the whole distribution of the outcome. <span class="math display">\[ F⁡(y|X) = P(Y ≤ y|X) \]</span></p>
<div class="callout callout-style-default callout-note callout-titled" title="Vocabulary Note">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Vocabulary Note
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Covariates</strong> - are a set of predictors <span class="math inline">\(X\)</span> that may affect the outcome <span class="math inline">\(Y\)</span> that we are measuring.</li>
</ul>
</div>
</div>
<section id="mathematically-deriving-the-cpm" class="level3" data-number="5.4.1">
<h3 data-number="5.4.1" class="anchored" data-anchor-id="mathematically-deriving-the-cpm"><span class="header-section-number">5.4.1</span> Mathematically Deriving the CPM:</h3>
<p>Consider the <strong>Linear Transformation Model</strong> which is a regression model where for an outcome <span class="math inline">\(Y\)</span> which is not assumed to be linear. There is some unknown increasing <strong>monotone transformation</strong> <span class="math inline">\(H\)</span> which follows a linear model that is applied to the outcome with errors that have a known distribution (we define the distribution of the error terms). <span class="math display">\[
\begin{aligned}
&amp; Y = H(Y^*) \\
&amp; Y^* = \beta^\top X + \epsilon \\
&amp; Y = H(\beta^\top X + \epsilon) \\
&amp; \epsilon \sim F_\epsilon
\end{aligned}
\]</span></p>
<div class="callout callout-style-default callout-note callout-titled" title="Vocabulary Note">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Vocabulary Note
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Monotone transformation/Monotone function</strong> - transformation or function <span class="math inline">\(H\)</span> which preserves the order.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Defining Variables">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Defining Variables
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><span class="math inline">\(Y\)</span> - Outcome/Continuous ordered predicted variable (increasing function).</li>
<li><span class="math inline">\(Y^*\)</span> - Unobserved continuous variable (underlying/hidden relationship function of the data).</li>
<li><span class="math inline">\(X\)</span> - Vector of predictor variables</li>
<li><span class="math inline">\(y\)</span> - Cutoff threshold value</li>
<li><span class="math inline">\(H\)</span> - Unknown monotone increasing function/transformation.
<ul>
<li>Its shape is nonparametric. So, <span class="math inline">\(H(.)\)</span> is a nonparametric transformation or shift from the baseline distribution.</li>
</ul></li>
<li><span class="math inline">\(\epsilon\)</span> - Random error. Assumed to come from some distribution. We specify this.
<ul>
<li>For ex. Normal error distribution <span class="math inline">\(ϵ \sim N(0,1)\)</span> → probit link</li>
</ul></li>
<li><span class="math inline">\(F_\epsilon\)</span> - Distribution function</li>
<li><span class="math inline">\(\beta\)</span> - Vector of the regression coefficients which describe how predictors shift the baseline distribution.</li>
<li><span class="math inline">\(\alpha(y)\)</span> - Monotone function of the outcome threshold y estimated directly from the data, this captures the marginal distribution without assuming normality or any other parametric form. It is a different intercept for each cutoff threshold vlaue <span class="math inline">\(y\)</span></li>
</ul>
</div>
</div>
<p>Vectors of predictor variables, regression coefficients, and transpose regression coefficients in matrix form: <span class="math display">\[
X =
\begin{bmatrix}
X_1 \\ \vdots \\ X_n
\end{bmatrix},
\qquad
\beta =
\begin{bmatrix}
\beta_1 \\ \vdots \\ \beta_n
\end{bmatrix},
\qquad
\beta^T =
\begin{bmatrix}
\beta_1 \cdot \cdot \cdot \beta_n
\end{bmatrix}
\]</span> Therefore, the linear transformation can be epxressed via the matrices: <span class="math display">\[
\begin{bmatrix}
y_1 \\
\vdots \\
y_n
\end{bmatrix}
=
\begin{bmatrix}
\beta_1 &amp; \cdots &amp; \beta_n
\end{bmatrix}
\begin{bmatrix}
X_1 \\
\vdots \\
X_n
\end{bmatrix}
+
\begin{bmatrix}
\epsilon_1 \\
\vdots \\
\epsilon_n
\end{bmatrix}
→
Y = \beta^T X + \epsilon_i
\]</span> The cummulative CDF of Y can be defined as: <span class="math display">\[
\begin{aligned}
&amp; F(y \mid X) = P(Y \leq y \mid X) \\
&amp; F(y \mid X) = P\left[H(\beta^\top X + \epsilon) \leq y \mid X\right] \\
&amp; F(y \mid X) = P\left[\epsilon \leq H^{-1}(y) - \beta^\top X \mid X\right] \\
&amp; F(y \mid X) = F_{\epsilon}\left[H^{-1}(y) - \beta^\top X\right]
\end{aligned}
\]</span></p>
<p>A probability is constrained between between 0 and 1, but the linear part <span class="math inline">\((\alpha(y) − \beta^TX)\)</span> can be any number. Where <span class="math inline">\(\alpha(y) = H^{-1}(y)\)</span> is the transformation/intercept function. So we apply a <strong>link function</strong> <span class="math inline">\(G = F_\epsilon^{-1}\)</span> by taking the inverse of <span class="math inline">\(F_𝜖\)</span> for both sides of the equation to stretch the probability onto the whole number line so that it can be written as a linear model. <span class="math display">\[
\begin{aligned}
&amp; F_\epsilon^{-1}\left[P(Y \leq y \mid X)\right] = F_\epsilon^{-1}\left[F_\epsilon(H^{-1}(y) - \beta^\top X)\right] \\
&amp; F_\epsilon^{-1}\left[P(Y \leq y \mid X)\right] = H^{-1}(y) - \beta^\top X \\
&amp; G\left[P(Y \leq y \mid X)\right] = H^{-1}(y) - \beta^\top X \\
&amp; G\left[P(Y \leq y \mid X)\right] = \alpha(y) - \beta^\top X
\end{aligned}
\]</span></p>
<div class="callout callout-style-default callout-note callout-titled" title="Vocabulary Note">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Vocabulary Note
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Link Function</strong> - is simply a mathematical function that transforms a probability into a scale that can be modeled using a linear predictor. It is a transformation function using some underlying distribution assumption.</li>
<li><strong>Link</strong> - connects the probability we’re interested in to the scale on which we can use a linear predictor.</li>
</ul>
</div>
</div>
<p>The CPM is the linear transformation model in another parameterized form: <span class="math display">\[
P(Y≤y∣X) → \text{link function G} →
\underbrace{G\left[P(Y \leq y \mid X)\right]}_{\text{link-transformed probability}}
=
\underbrace{\alpha(y)}_{\text{cutoff-specific intercept}} - \underbrace{\beta^T X}_{\text{effect of predictors}}
\]</span></p>
</section>
<section id="relation-between-the-cpm-and-being-semiparametric" class="level3" data-number="5.4.2">
<h3 data-number="5.4.2" class="anchored" data-anchor-id="relation-between-the-cpm-and-being-semiparametric"><span class="header-section-number">5.4.2</span> Relation Between the CPM and Being Semiparametric:</h3>
<p>A convenient property of this model is that it uses only the <strong>order</strong> of the outcome <span class="math inline">\(Y\)</span>. Because <span class="math inline">\(H\)</span> is increasing, applying any monotonic transformation to <span class="math inline">\(Y\)</span> leaves the model’s results unchanged, so we never have to choose a transformation ourselves.</p>
<p>The <a href="#tbl-transformations" class="quarto-xref">Table&nbsp;<span>5.1</span></a> shows the transformations <span class="math inline">\(\alpha(y) = H^{-1}(y)\)</span> that a researcher might otherwise have to pick. The CPM estimates <span class="math inline">\(\alpha(y)\)</span> directly.</p>
<div id="tbl-transformations" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-transformations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.1: Possible transformations of the outcome
</figcaption>
<div aria-describedby="tbl-transformations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 53%">
<col style="width: 46%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Transformation of <span class="math inline">\(Y\)</span>: <span class="math inline">\(\alpha(y) = H^{-1}(y)\)</span></th>
<th style="text-align: left;">Resulting regression</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\alpha(y) = y\)</span> (none)</td>
<td style="text-align: left;">Ordinary linear regression</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\alpha(y) = \log(y)\)</span></td>
<td style="text-align: left;">Log-linear regression</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\alpha(y) = \text{Box-Cox}(y)\)</span></td>
<td style="text-align: left;">Box-Cox regression</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\alpha(y)\)</span> unknown</td>
<td style="text-align: left;">The CPM, which estimates the transformation from the data</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>As y gets bigger, the probability of being at or below y goes up, so <span class="math inline">\(\alpha(y)\)</span> must increase too (The CDF increeases). <span class="math inline">\(\alpha(y)\)</span> is the <strong>baseline link-transformed CDF</strong>. For cases when <span class="math inline">\(X = 0\)</span>, The <span class="math inline">\(\beta^T X\)</span> term vanishes.</p>
<p><span class="math display">\[G\left[P(Y \leq y \mid X=0)\right] = \alpha(y)\]</span> Since <span class="math inline">\(\alpha(y)\)</span> must rise as <span class="math inline">\(y\)</span> rises, the <span class="math inline">\(\alpha(y)\)</span> term is described as <strong>nonparametric</strong> where we observe <span class="math inline">\(\alpha_1 \le \alpha_2 \le \dots \le \alpha_n\)</span>.</p>
<p>The CPM <span class="math inline">\(G\left[P(Y \leq y \mid X)\right] = \alpha(y) - \beta^\top X\)</span> is <strong>semiparametric</strong>:</p>
<ul>
<li><span class="math inline">\(\beta^T X\)</span> is <strong>parametric</strong>: a finite set of coefficients describing the effect of the predictors.</li>
<li><span class="math inline">\(\alpha(y)\)</span> is <strong>nonparametric</strong>: an unspecified increasing function estimated from the data.</li>
<li>The link function <span class="math inline">\(G\)</span> is chosen by the analyst and determines the assumed error distribution.</li>
</ul>
</section>
<section id="choosing-the-link-function" class="level3" data-number="5.4.3">
<h3 data-number="5.4.3" class="anchored" data-anchor-id="choosing-the-link-function"><span class="header-section-number">5.4.3</span> Choosing the Link Function:</h3>
<p>Recall that the link function is <span class="math inline">\(G = F_\epsilon^{-1}\)</span>. This means choosing a link function is the same as choosing the distribution of the errors <span class="math inline">\(\epsilon\)</span> on the transformed scale. <a href="#tbl-links" class="quarto-xref">Table&nbsp;<span>5.2</span></a> lists the most common choices.</p>
<div id="tbl-links" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-links-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.2: Commonly used link functions and their corresponding error distributions.
</figcaption>
<div aria-describedby="tbl-links-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 31%">
<col style="width: 28%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Name</th>
<th style="text-align: left;">Link function <span class="math inline">\(G(p)\)</span></th>
<th style="text-align: left;">Error distribution</th>
<th style="text-align: left;">CDF <span class="math inline">\(F_\epsilon(y)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">logit</td>
<td style="text-align: left;"><span class="math inline">\(\log\left[\dfrac{p}{1-p}\right]\)</span></td>
<td style="text-align: left;">Logistic</td>
<td style="text-align: left;"><span class="math inline">\(\dfrac{\exp(y)}{1+\exp(y)}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">probit</td>
<td style="text-align: left;"><span class="math inline">\(\Phi^{-1}(p)\)</span></td>
<td style="text-align: left;">Normal</td>
<td style="text-align: left;"><span class="math inline">\(\Phi(y)\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">loglog</td>
<td style="text-align: left;"><span class="math inline">\(-\log\left[-\log(p)\right]\)</span></td>
<td style="text-align: left;">Extreme value type 2 (Gumbel maximum)</td>
<td style="text-align: left;"><span class="math inline">\(\exp\left[-\exp(-y)\right]\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">cloglog</td>
<td style="text-align: left;"><span class="math inline">\(\log\left[-\log(1-p)\right]\)</span></td>
<td style="text-align: left;">Extreme value type 1 (Gumbel minimum)</td>
<td style="text-align: left;"><span class="math inline">\(1-\exp\left[-\exp(y)\right]\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<ul>
<li><strong>Each row is one assumption about the error distribution.</strong> The <strong>CDF</strong> column is <span class="math inline">\(F_\epsilon\)</span>, and the <strong>link function</strong> column is its inverse, <span class="math inline">\(G = F_\epsilon^{-1}\)</span>.
<ul>
<li><strong>Example (logit):</strong> If the errors are logistic, then <span class="math inline">\(p = F_\epsilon(y) = \dfrac{e^y}{1+e^y}\)</span>. Solving for <span class="math inline">\(y\)</span> gives <span class="math inline">\(y = \log\left(\dfrac{p}{1-p}\right)\)</span>, which is the logit link.</li>
</ul></li>
<li><strong>Symmetric assumptions depend on error distribution.</strong>
<ul>
<li>The logit and probit assume symmetric, bell-shaped errors. The loglog and cloglog assume skewed errors, skewed in opposite directions.</li>
</ul></li>
<li><strong>Interpretation of <span class="math inline">\(\beta\)</span> depends on the link.</strong>
<ul>
<li>With the logit link, <span class="math inline">\(\beta\)</span> is a log-odds ratio. With the cloglog link, <span class="math inline">\(\beta\)</span> is a log-hazard ratio.</li>
</ul></li>
<li><strong>The transformation <span class="math inline">\(\alpha(y)\)</span> is left unspecified, but the link <span class="math inline">\(G\)</span> is not.</strong></li>
</ul>
</section>
</section>
<section id="model-demonstration-in-code---single-dataset-evaluation-of-the-cpm" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="model-demonstration-in-code---single-dataset-evaluation-of-the-cpm"><span class="header-section-number">5.5</span> Model Demonstration in Code - Single Dataset Evaluation of the CPM:</h2>
<p><strong>Goal:</strong> build one simulated dataset, fit the ordinal regression cumulative probability model (CPM) on part of it, and then measure how well it predicts the part it has never seen.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Vocabulary Note">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Vocabulary Note
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Training set</strong> - the portion of the data the model ;earns from.</li>
<li><strong>Test set</strong> - the portion of the data set that the model is not trained on. We use it afterward to test the model see how the model does on new observations it has not seen before. This is called <strong>out-of-sample performance</strong>.</li>
<li><strong>Prediction rule</strong> - a specific threshold/cutoff derived from a model to classify datapoints. It turns predictor values <span class="math inline">\(X\)</span> into a prediction. A linear regression has one prediction rule which is a fitted line. The CPM has several prediction rules, because it estimates the whole conditional distribution: we can read off a mean, a median, a probability, etc.</li>
</ul>
</div>
</div>
<section id="step-1-the-data-generating-process" class="level3" data-number="5.5.1">
<h3 data-number="5.5.1" class="anchored" data-anchor-id="step-1-the-data-generating-process"><span class="header-section-number">5.5.1</span> Step 1: The Data-Generating Process</h3>
<p>Because we simulate the data, we get to be “the master of the universe”: we pick the true relationship, and later we can check how close the model gets to it. This is the same structure as the paper’s linear transformation model:</p>
<p><span class="math display">\[
Y^* = \beta^\top X + \epsilon, \qquad \epsilon \sim N(0,1), \qquad Y = H(Y^*) = \exp(Y^*)
\]</span></p>
<ul>
<li><strong>Three predictors:</strong>
<ul>
<li><span class="math inline">\(X_1 \sim \text{Bernoulli}(0.5)\)</span>: a binary variable, the household head has a bachelor’s degree
<ul>
<li>X₁ = 1 is yes with probability of p = 0.5</li>
<li>X₁ = 0 is no with probability of p = 0.5</li>
</ul></li>
<li><span class="math inline">\(X_2, X_3 \sim N(0,1)\)</span>: two continuous variables, <span class="math inline">\(X_2\)</span> is the local unemployment rate and <span class="math inline">\(X_3\)</span> is the household head’s years of work experience respectively</li>
</ul></li>
<li><strong>Outcome:</strong>
<ul>
<li><span class="math inline">\(Y\)</span> is a skewed, positive variable for the annual household income, measured in units of $50,000.</li>
</ul></li>
<li><strong>True coefficients:</strong> <span class="math inline">\(\beta = (1.0,\,-0.5,\,0.5)\)</span>.
<ul>
<li><span class="math inline">\(\beta_1 = 1.0\)</span>: having a degree pushes income <strong>up</strong>.</li>
<li><span class="math inline">\(\beta_2 = -0.5\)</span>: a <strong>higher</strong> local unemployment rate pushes income <strong>down</strong>.</li>
<li><span class="math inline">\(\beta_3 = 0.5\)</span>: <strong>more</strong> work experience pushes income <strong>up</strong>.</li>
</ul></li>
<li><strong>Why <span class="math inline">\(H(y)=\exp(y)\)</span>?</strong> It makes the outcome <span class="math inline">\(Y\)</span> right-skewed, just like real income. A plain linear regression on <span class="math inline">\(Y\)</span> would be a poor fit because the <em>correct transformation</em> is <span class="math inline">\(\log(Y)\)</span>, a very common choice for income. The CPM is never told this; it has to discover the transformation from the data.</li>
</ul>
<p>Because we know the truth, we can write down the <em>exact</em> answers that any model is trying to estimate. Since <span class="math inline">\(Y = \exp(\beta^\top X + \epsilon)\)</span>:</p>
<div id="tbl-truth" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-truth-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.3: True conditional summaries under this data-generating process
</figcaption>
<div aria-describedby="tbl-truth-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 45%">
<col style="width: 54%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Quantity</th>
<th style="text-align: left;">True value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Median of <span class="math inline">\(Y \mid X\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\exp(\beta^\top X)\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Mean of <span class="math inline">\(Y \mid X\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\exp(\beta^\top X + \tfrac{1}{2})\)</span> (a log-normal mean, with <span class="math inline">\(\sigma=1\)</span>)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(P(Y &gt; c \mid X)\)</span></td>
<td style="text-align: left;"><span class="math inline">\(1 - \Phi\left(\log c - \beta^\top X\right)\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="step1-dgp" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.optimize <span class="im">import</span> minimize</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> norm, kstest</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>TRUE_BETA <span class="op">=</span> np.array([<span class="fl">1.0</span>, <span class="op">-</span><span class="fl">0.5</span>, <span class="fl">0.5</span>])  <span class="co"># true coefficients of the data-generating process</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> simulate_data(n, beta<span class="op">=</span>TRUE_BETA, rng<span class="op">=</span><span class="va">None</span>):</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Simulate n households: returns the predictor matrix X (n x 3) and outcome y (n,)."""</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    rng <span class="op">=</span> np.random.default_rng() <span class="cf">if</span> rng <span class="kw">is</span> <span class="va">None</span> <span class="cf">else</span> rng</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    x1 <span class="op">=</span> rng.binomial(<span class="dv">1</span>, <span class="fl">0.5</span>, size<span class="op">=</span>n).astype(<span class="bu">float</span>)    <span class="co"># bachelor's degree: 1 = yes, 0 = no</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    x2 <span class="op">=</span> rng.normal(<span class="dv">0</span>, <span class="dv">1</span>, size<span class="op">=</span>n)                      <span class="co"># local unemployment rate </span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    x3 <span class="op">=</span> rng.normal(<span class="dv">0</span>, <span class="dv">1</span>, size<span class="op">=</span>n)                      <span class="co"># years of work experience </span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    X <span class="op">=</span> np.column_stack([x1, x2, x3])                  <span class="co"># one row per household, one column per predictor (income)</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    eps <span class="op">=</span> rng.normal(<span class="dv">0</span>, <span class="dv">1</span>, size<span class="op">=</span>n)                     <span class="co"># random error, N(0,1)</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    ystar <span class="op">=</span> X <span class="op">@</span> beta <span class="op">+</span> eps                             <span class="co"># hidden Y* = beta'X + error</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> np.exp(ystar)                                  <span class="co"># observed Y = H(Y*) = exp(Y*)</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> X, y</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">2026</span>)   <span class="co"># fixed seed so the results are reproducible</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>X, y <span class="op">=</span> simulate_data(<span class="dv">600</span>, rng<span class="op">=</span>rng)  <span class="co"># runs the data-generating process where n = 600 households</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"y: min=</span><span class="sc">{</span>y<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.2f}</span><span class="ss">  median=</span><span class="sc">{</span>np<span class="sc">.</span>median(y)<span class="sc">:.2f}</span><span class="ss">  mean=</span><span class="sc">{</span>y<span class="sc">.</span>mean()<span class="sc">:.2f}</span><span class="ss">  max=</span><span class="sc">{</span>y<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.2f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>y: min=0.03  median=1.56  mean=3.64  max=37.98</code></pre>
</div>
</div>
<p>Notice that the mean is noticeably larger than the median and the maximum is far out in the tail. That is what right-skew looks like. * Smallest household income: 0.03 × $50,000 = $1,500 * Mean income: 3.64 × $50,000 = $182,000 * Median income: 1.56 × $50,000 = $78,000 * Largest household income: 37.98 × $50,000 ≈ $1.9 million</p>
<p>Refer to the Diagram below. The left panel show the distribution of the household income data. The right panel shows <span class="math inline">\(\log(y)\)</span>, which is exactly the hidden <span class="math inline">\(Y^*\)</span> (since <span class="math inline">\(Y = \exp(Y^*)\)</span>). On that scale the distribution is a symmetric bell shape. That symmetric scale is what the CPM has to uncover on its own.</p>
<div id="cell-fig-skew" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">4</span>))</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].hist(y, bins<span class="op">=</span><span class="dv">40</span>, edgecolor<span class="op">=</span><span class="st">"white"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].axvline(np.median(y), color<span class="op">=</span><span class="st">"k"</span>, ls<span class="op">=</span><span class="st">":"</span>,  lw<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="ss">f"median = </span><span class="sc">{</span>np<span class="sc">.</span>median(y)<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].axvline(y.mean(),     color<span class="op">=</span><span class="st">"r"</span>, ls<span class="op">=</span><span class="st">"--"</span>, lw<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="ss">f"mean = </span><span class="sc">{</span>y<span class="sc">.</span>mean()<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xlabel(<span class="st">"y (income, in $50,000 units)"</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"number of households for bin size 40"</span>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"Income (right-skewed)"</span>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].legend()</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].hist(np.log(y), bins<span class="op">=</span><span class="dv">40</span>, edgecolor<span class="op">=</span><span class="st">"white"</span>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].axvline(np.median(np.log(y)), color<span class="op">=</span><span class="st">"k"</span>, ls<span class="op">=</span><span class="st">":"</span>,  lw<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">"median"</span>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].axvline(np.log(y).mean(),     color<span class="op">=</span><span class="st">"r"</span>, ls<span class="op">=</span><span class="st">"--"</span>, lw<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">"mean"</span>)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xlabel(<span class="st">"log(y)"</span>)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"log(income) (roughly symmetric)"</span>)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].legend()</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-skew" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-skew-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ordinal_regression_files/figure-html/fig-skew-output-1.png" width="951" height="374" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-skew-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.1: Left: income is right-skewed, so the mean (dashed) is pulled above the median (dotted). Right: on the log scale the distribution is roughly symmetric.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="step-2-traintest-split" class="level3" data-number="5.5.2">
<h3 data-number="5.5.2" class="anchored" data-anchor-id="step-2-traintest-split"><span class="header-section-number">5.5.2</span> Step 2: Train/Test Split</h3>
<p>If we judged the model on the same data it learned from, it could look great simply because it memorized quirks of that sample. So we randomly set aside 30% of the observations as a test set. The model never sees them during fitting.</p>
<div id="step2-split" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>idx <span class="op">=</span> rng.permutation(<span class="bu">len</span>(y))       <span class="co"># shuffle the row numbers 0..599 before splitting the data</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>n_train <span class="op">=</span> <span class="bu">int</span>(<span class="fl">0.7</span> <span class="op">*</span> <span class="bu">len</span>(y))         <span class="co"># 420 rows for training (70% for training, 30% for splitting)</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>train_idx, test_idx <span class="op">=</span> idx[:n_train], idx[n_train:]</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>X_train, y_train <span class="op">=</span> X[train_idx], y[train_idx]</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>X_test,  y_test  <span class="op">=</span> X[test_idx],  y[test_idx]</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"training rows: </span><span class="sc">{</span><span class="bu">len</span>(y_train)<span class="sc">}</span><span class="ss">   test rows: </span><span class="sc">{</span><span class="bu">len</span>(y_test)<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>training rows: 420   test rows: 180</code></pre>
</div>
</div>
</section>
<section id="step-3-fit-the-cpm-on-the-training-set" class="level3" data-number="5.5.3">
<h3 data-number="5.5.3" class="anchored" data-anchor-id="step-3-fit-the-cpm-on-the-training-set"><span class="header-section-number">5.5.3</span> Step 3: Fit the CPM on the Training Set</h3>
<p>We use the probit link. Recall, the <strong>link function</strong> is a translator between probabilities and the linear translation the model is built on. The <strong>probit link</strong> is the version of that translation that <strong>assumes normally distributed errors</strong>. which matches our true <span class="math inline">\(N(0,1)\)</span> errors:</p>
<p><span class="math display">\[
P(Y \le y \mid X) = \Phi\left(\alpha(y) - \beta^\top X\right)
\]</span></p>
<div class="callout callout-style-default callout-note callout-titled" title="Review of the Probit Link">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Review of the Probit Link
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>The <strong>probit link</strong> is Φ⁻¹, the <strong>inverse of the standard normal CDF.</strong>
<ul>
<li><span class="math inline">\(Φ\)</span> (the normal CDF) takes any number z and returns the probability that a standard normal value is at or below z.</li>
<li><span class="math inline">\(Φ⁻¹\)</span> (probit) goes the other way: it takes a probability and returns the z-score that corresponds to it.</li>
</ul></li>
<li>Probit stretches probabilities, which are trapped between 0 and 1, onto the whole number line, so they can match the formula. The model says:
<ul>
<li><span class="math inline">\(Φ⁻¹[P(Y ≤ y | X)] = α(y) − βᵀX\)</span></li>
</ul></li>
<li>and applying Φ to both sides gives the form:
<ul>
<li><span class="math inline">\(P(Y ≤ y | X) = Φ(α(y) − βᵀX)\)</span></li>
</ul></li>
</ul>
</div>
</div>
<p><strong>What the model has to estimate</strong></p>
<ul>
<li><span class="math inline">\(\beta\)</span>: now a vector of <strong>3</strong> numbers instead of a single number.</li>
<li><span class="math inline">\(\alpha_1 &lt; \alpha_2 &lt; \dots &lt; \alpha_{n-1}\)</span>: one intercept for every observed training outcome (the paper’s nonparametric <span class="math inline">\(\alpha(y)\)</span>). The last one, <span class="math inline">\(\alpha_n\)</span>, is fixed at <span class="math inline">\(+\infty\)</span> so the CDF reaches 1 at the largest observed <span class="math inline">\(y\)</span>.</li>
</ul>
<p><strong>Determining maximum likelihood.</strong> Imagine sorting the households by <span class="math inline">\(Y\)</span>. Household <span class="math inline">\(i\)</span>’s outcome sits in the slice between cutoffs <span class="math inline">\(\alpha_{i-1}\)</span> and <span class="math inline">\(\alpha_i\)</span>, so under the model their data has probability:</p>
<p><span class="math display">\[
\Phi(\alpha_i - \beta^\top x_i) - \Phi(\alpha_{i-1} - \beta^\top x_i).
\]</span></p>
<p>The <strong>likelihood</strong> multiplies these probabilities over all households. We search for the <span class="math inline">\(\beta\)</span> and <span class="math inline">\(\alpha\)</span> values that make the observed data as probable as possible (maximum likelihood).</p>
<p><strong>To fit the model we need:</strong></p>
<ul>
<li><ol type="1">
<li><strong>Create an optimizer.</strong> The optimizer (a searching algorithm) tries many candidate values for β and the α’s and keeps improving until it finds the ones that make the training data most probable. The α’s are cutoffs tied to the sorted incomes, so they must go up: α₁ &lt; α₂ &lt; α₃ &lt; … to be a valid CDF. But the optimizer doesn’t know that rule. It treats every number as free and might try something like α₂ = −3 right after α₁ = 2.</li>
</ol></li>
<li><ol start="2" type="1">
<li><strong>Keeping the intercepts increasing.</strong> The optimizer is free to try any numbers, but the <span class="math inline">\(\alpha\)</span>’s must be ordered. Don’t let the optimizer choose the α’s directly. Let it choose:</li>
</ol>
<ul>
<li>θ₀, any number, which becomes the first α;</li>
<li>θ₁, θ₂, …, any numbers, which become the gaps between consecutive α’s.</li>
<li>The code turns each θ into positive gaps <span class="math inline">\(e^{\theta_1}, e^{\theta_2}, \dots\)</span>, no matter what number goes in. The α’s are then rebuilt by adding up gaps: <span class="math inline">\(\alpha_j = \theta_0 + \sum e^{\theta_m}\)</span>.
<ul>
<li>α₁ = θ₀</li>
<li>α₂ = θ₀ + e^θ₁</li>
<li>α₃ = θ₀ + e^θ₁ + e^θ₂</li>
</ul></li>
</ul></li>
<li><ol start="3" type="1">
<li><strong>An analytic gradient.</strong> The gradient tells the optimizer which direction improves the likelihood. Giving it the exact formula (instead of letting it guess numerically) makes fitting hundreds of intercepts very fast.</li>
</ol></li>
<li><ol start="4" type="1">
<li><strong>A stable probability formula</strong> Each household’s likelihood contribution is Φ(upper) − Φ(lower), the probability of landing in a thin slice. When both values are far out in the upper tail, Φ is essentially 1 for both, and the computer can only store a limited number of digits. For example, Φ(10) and Φ(11) both round to exactly 1.0, so their difference comes out as 0. Then the log of that is log(0) = −∞, which breaks the search. Use the survival function, sf(z) = 1 − Φ(z), the probability of being above z.</li>
</ol></li>
</ul>
<div id="step3-fit" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> _interval_prob(upper, lower):</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Phi(upper) - Phi(lower), computed in a numerically stable way."""</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.where(lower <span class="op">&gt;</span> <span class="dv">0</span>,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>                    norm.sf(lower) <span class="op">-</span> norm.sf(upper),</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>                    norm.cdf(upper) <span class="op">-</span> norm.cdf(lower))</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> _unpack(params, p):</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Split the optimizer's vector into beta and the increasing alphas."""</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    beta <span class="op">=</span> params[:p]</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    theta <span class="op">=</span> params[p:]</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    gaps <span class="op">=</span> np.exp(theta[<span class="dv">1</span>:])                                           <span class="co"># positive gaps</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    alpha <span class="op">=</span> np.concatenate([[theta[<span class="dv">0</span>]], theta[<span class="dv">0</span>] <span class="op">+</span> np.cumsum(gaps)])   <span class="co"># increasing alphas</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> beta, gaps, alpha</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> _neg_loglik(params, X):</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Negative log-likelihood and its gradient (X must be sorted by y)."""</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>    n, p <span class="op">=</span> X.shape</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>    beta, gaps, alpha <span class="op">=</span> _unpack(params, p)</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>    eta <span class="op">=</span> X <span class="op">@</span> beta                                   <span class="co"># beta'x for every person</span></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>    upper <span class="op">=</span> np.append(alpha, np.inf) <span class="op">-</span> eta           <span class="co"># alpha_i - beta'x_i</span></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>    lower <span class="op">=</span> np.insert(alpha, <span class="dv">0</span>, <span class="op">-</span>np.inf) <span class="op">-</span> eta       <span class="co"># alpha_{i-1} - beta'x_i</span></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>    prob <span class="op">=</span> np.maximum(_interval_prob(upper, lower), <span class="fl">1e-300</span>)</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>    loglik <span class="op">=</span> np.<span class="bu">sum</span>(np.log(prob))</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>    phi_u, phi_l <span class="op">=</span> norm.pdf(upper), norm.pdf(lower)</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>    d_beta <span class="op">=</span> X.T <span class="op">@</span> ((phi_l <span class="op">-</span> phi_u) <span class="op">/</span> prob)                         <span class="co"># slope of loglik wrt beta</span></span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>    g_alpha <span class="op">=</span> phi_u[:<span class="op">-</span><span class="dv">1</span>] <span class="op">/</span> prob[:<span class="op">-</span><span class="dv">1</span>] <span class="op">-</span> phi_l[<span class="dv">1</span>:] <span class="op">/</span> prob[<span class="dv">1</span>:]         <span class="co"># slope wrt each alpha</span></span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>    rev <span class="op">=</span> np.cumsum(g_alpha[::<span class="op">-</span><span class="dv">1</span>])[::<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>    grad <span class="op">=</span> np.concatenate([d_beta, [g_alpha.<span class="bu">sum</span>()], gaps <span class="op">*</span> rev[<span class="dv">1</span>:]])  <span class="co"># chain rule back to theta</span></span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span>loglik, <span class="op">-</span>grad</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> fit_cpm_probit(X, y):</span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Fit a probit CPM. Returns a dictionary describing the fitted model."""</span></span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>    order <span class="op">=</span> np.argsort(y)                       <span class="co"># the CPM only uses the ORDER of y</span></span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a>    Xs, ys <span class="op">=</span> X[order], y[order]</span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a>    n, p <span class="op">=</span> Xs.shape</span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a>    a0 <span class="op">=</span> norm.ppf(np.arange(<span class="dv">1</span>, n) <span class="op">/</span> n)          <span class="co"># sensible starting values for the alphas</span></span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a>    start <span class="op">=</span> np.concatenate([np.zeros(p), [a0[<span class="dv">0</span>]], np.log(np.diff(a0))])</span>
<span id="cb6-39"><a href="#cb6-39" aria-hidden="true" tabindex="-1"></a>    res <span class="op">=</span> minimize(_neg_loglik, start, args<span class="op">=</span>(Xs,), jac<span class="op">=</span><span class="va">True</span>, method<span class="op">=</span><span class="st">"L-BFGS-B"</span>,</span>
<span id="cb6-40"><a href="#cb6-40" aria-hidden="true" tabindex="-1"></a>                   options<span class="op">=</span>{<span class="st">"maxiter"</span>: <span class="dv">10000</span>, <span class="st">"maxfun"</span>: <span class="dv">50000</span>})</span>
<span id="cb6-41"><a href="#cb6-41" aria-hidden="true" tabindex="-1"></a>    beta, gaps, alpha <span class="op">=</span> _unpack(res.x, p)</span>
<span id="cb6-42"><a href="#cb6-42" aria-hidden="true" tabindex="-1"></a>    alpha <span class="op">=</span> np.append(alpha, np.inf)            <span class="co"># alpha_n = +infinity</span></span>
<span id="cb6-43"><a href="#cb6-43" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> {<span class="st">"beta"</span>: beta, <span class="st">"alpha"</span>: alpha, <span class="st">"y"</span>: ys, <span class="st">"converged"</span>: res.success}</span>
<span id="cb6-44"><a href="#cb6-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-45"><a href="#cb6-45" aria-hidden="true" tabindex="-1"></a>cpm <span class="op">=</span> fit_cpm_probit(X_train, y_train)</span>
<span id="cb6-46"><a href="#cb6-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-47"><a href="#cb6-47" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"converged:"</span>, cpm[<span class="st">"converged"</span>])</span>
<span id="cb6-48"><a href="#cb6-48" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"true beta:     "</span>, TRUE_BETA)</span>
<span id="cb6-49"><a href="#cb6-49" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"estimated beta:"</span>, np.<span class="bu">round</span>(cpm[<span class="st">"beta"</span>], <span class="dv">3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>converged: True
true beta:      [ 1.  -0.5  0.5]
estimated beta: [ 1.157 -0.584  0.52 ]</code></pre>
</div>
</div>
<p>The estimated <span class="math inline">\(\hat\beta\)</span> should land near the true values. They won’t match exactly, because 420 observations carry random noise.</p>
<p><strong>Did the CPM discover the log transformation?</strong> Under this data-generating process, <span class="math inline">\(\alpha(y) = H^{-1}(y) = \log(y)\)</span> exactly. The CPM was never told this. If it works, the estimated step function <span class="math inline">\(\hat\alpha(y)\)</span> should trace out <span class="math inline">\(\log(y)\)</span>:</p>
<div id="cell-fig-alpha" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>ys <span class="op">=</span> cpm[<span class="st">"y"</span>][:<span class="op">-</span><span class="dv">1</span>]            <span class="co"># drop the last point (alpha is +infinity there)</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>alpha_hat <span class="op">=</span> cpm[<span class="st">"alpha"</span>][:<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">5</span>, <span class="dv">4</span>))</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>ax.step(ys, alpha_hat, where<span class="op">=</span><span class="st">"post"</span>, label<span class="op">=</span><span class="vs">r"estimated </span><span class="dv">$</span><span class="er">\</span><span class="vs">hat</span><span class="ch">\a</span><span class="vs">lpha</span><span class="kw">(</span><span class="vs">y</span><span class="kw">)</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>ax.plot(ys, np.log(ys), <span class="st">"k:"</span>, label<span class="op">=</span><span class="vs">r"true </span><span class="dv">$</span><span class="er">\</span><span class="vs">log</span><span class="kw">(</span><span class="vs">y</span><span class="kw">)</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>ax.set_xscale(<span class="st">"log"</span>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"y (log scale)"</span>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="vs">r"</span><span class="dv">$</span><span class="ch">\a</span><span class="vs">lpha</span><span class="kw">(</span><span class="vs">y</span><span class="kw">)</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>ax.legend()</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div id="fig-alpha" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-alpha-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="ordinal_regression_files/figure-html/fig-alpha-output-1.png" width="440" height="359" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-alpha-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.2: The CPM’s estimated transformation closely follows the true transformation log(y).
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="step-4-prediction-rules-from-the-fitted-cdf" class="level3" data-number="5.5.4">
<h3 data-number="5.5.4" class="anchored" data-anchor-id="step-4-prediction-rules-from-the-fitted-cdf"><span class="header-section-number">5.5.4</span> Step 4: Prediction Rules from the Fitted CDF</h3>
<p>A CPM doesn’t output one number. For any household’s with predictors <span class="math inline">\(x\)</span>, it outputs an entire estimated CDF over the training outcomes <span class="math inline">\(y_1 &lt; y_2 &lt; \dots\)</span>:</p>
<p><span class="math display">\[
\hat F(y_i \mid x) = \Phi\left(\hat\alpha_i - \hat\beta^\top x\right)
\]</span></p>
<p>From that one curve we can read off several prediction rules:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 73%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Prediction rule</th>
<th style="text-align: left;">How it is computed from <span class="math inline">\(\hat F(\cdot \mid x)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Conditional mean</strong></td>
<td style="text-align: left;">The CDF jumps by <span class="math inline">\(\hat f_i = \hat F(y_i) - \hat F(y_{i-1})\)</span> at each <span class="math inline">\(y_i\)</span>. That is the probability of <span class="math inline">\(y_i\)</span>. The mean is <span class="math inline">\(\sum_i y_i \hat f_i\)</span>.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Conditional median</strong></td>
<td style="text-align: left;">The <span class="math inline">\(y\)</span> where <span class="math inline">\(\hat F\)</span> crosses 0.5.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Tail probability</strong></td>
<td style="text-align: left;"><span class="math inline">\(\hat P(Y &gt; c \mid x) = 1 - \hat F(c \mid x)\)</span> for a cutoff <span class="math inline">\(c\)</span>.</td>
</tr>
</tbody>
</table>
<div id="step4-predict" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> predict_cdf(model, X_new):</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Row j = estimated CDF of test person j, evaluated at every training y."""</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    eta <span class="op">=</span> X_new <span class="op">@</span> model[<span class="st">"beta"</span>]</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> norm.cdf(model[<span class="st">"alpha"</span>][<span class="va">None</span>, :] <span class="op">-</span> eta[:, <span class="va">None</span>])    <span class="co"># shape (n_new, n_train)</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> predict_mean(model, X_new):</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    F <span class="op">=</span> predict_cdf(model, X_new)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    f <span class="op">=</span> np.diff(F, axis<span class="op">=</span><span class="dv">1</span>, prepend<span class="op">=</span><span class="fl">0.0</span>)         <span class="co"># probability at each training y</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> f <span class="op">@</span> model[<span class="st">"y"</span>]                       <span class="co"># sum of y_i * f_i</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> predict_quantile(model, X_new, q<span class="op">=</span><span class="fl">0.5</span>):</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    F <span class="op">=</span> predict_cdf(model, X_new)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.array([np.interp(q, row, model[<span class="st">"y"</span>]) <span class="cf">for</span> row <span class="kw">in</span> F])   <span class="co"># interpolated inverse CDF</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> cdf_at(model, X_new, y_values):</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Estimated F(y | x) at arbitrary y values (one per row), by linear interpolation."""</span></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>    F <span class="op">=</span> predict_cdf(model, X_new)</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>    y_values <span class="op">=</span> np.broadcast_to(y_values, (<span class="bu">len</span>(X_new),))</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.array([np.interp(yv, model[<span class="st">"y"</span>], row, left<span class="op">=</span><span class="fl">0.0</span>, right<span class="op">=</span><span class="fl">1.0</span>)</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>                     <span class="cf">for</span> row, yv <span class="kw">in</span> <span class="bu">zip</span>(F, y_values)])</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> predict_prob_above(model, X_new, c):</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="fl">1.0</span> <span class="op">-</span> cdf_at(model, X_new, c)</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a><span class="co"># A cutoff for the tail-probability rule: the 80th percentile of the training outcomes.</span></span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>c <span class="op">=</span> np.quantile(y_train, <span class="fl">0.80</span>)</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>cpm_mean   <span class="op">=</span> predict_mean(cpm, X_test)</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>cpm_median <span class="op">=</span> predict_quantile(cpm, X_test, <span class="fl">0.5</span>)</span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>cpm_prob   <span class="op">=</span> predict_prob_above(cpm, X_test, c)</span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a><span class="co"># The TRUE answers from the table in Step 1 (only possible because we simulated the data).</span></span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>eta_true    <span class="op">=</span> X_test <span class="op">@</span> TRUE_BETA</span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a>true_mean   <span class="op">=</span> np.exp(eta_true <span class="op">+</span> <span class="fl">0.5</span>)</span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a>true_median <span class="op">=</span> np.exp(eta_true)</span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a>true_prob   <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> norm.cdf(np.log(c) <span class="op">-</span> eta_true)</span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"cutoff c = </span><span class="sc">{</span>c<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"first 5 test people:"</span>)</span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"  CPM median :"</span>, np.<span class="bu">round</span>(cpm_median[:<span class="dv">5</span>], <span class="dv">2</span>))</span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"  true median:"</span>, np.<span class="bu">round</span>(true_median[:<span class="dv">5</span>], <span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>cutoff c = 5.47
first 5 test people:
  CPM median : [0.38 3.13 7.4  2.06 3.13]
  true median: [0.46 2.86 6.21 2.12 3.01]</code></pre>
</div>
</div>
</section>
<section id="step-5-out-of-sample-performance" class="level3" data-number="5.5.5">
<h3 data-number="5.5.5" class="anchored" data-anchor-id="step-5-out-of-sample-performance"><span class="header-section-number">5.5.5</span> Step 5: Out-of-Sample Performance</h3>
<p>We compare each prediction rule with what actually happened to the test households. Two reference points make the numbers meaningful:</p>
<ul>
<li><strong>Baseline (“ignore <span class="math inline">\(X\)</span>”):</strong> predict the same training mean / median / proportion for every household.</li>
<li><strong>Truth:</strong> use the <em>true</em> formulas from Step 1. Even perfect knowledge of the data-generating process can’t predict the random error <span class="math inline">\(\epsilon\)</span>, so this is the best score anyone could expect. The closer the CPM gets to it, the better.</li>
</ul>
<p><strong>The error measures</strong>:</p>
<ul>
<li><strong>MSE (mean squared error)</strong> for mean predictions: <span class="math inline">\(\frac{1}{m}\sum (y_j - \hat y_j)^2\)</span>. It punishes big misses heavily.</li>
<li><strong>MAE (mean absolute error)</strong> for median predictions: <span class="math inline">\(\frac{1}{m}\sum |y_j - \hat y_j|\)</span>. The median is the prediction that minimizes this.</li>
<li><strong>Brier score</strong> for the tail probability: the MSE between the predicted probability and what happened (1 if <span class="math inline">\(y_j &gt; c\)</span>, 0 otherwise).</li>
</ul>
<div id="step5-metrics" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> evaluate(mean_pred, median_pred):</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Score one set of predictions against the test outcomes."""</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> {<span class="st">"MSE (mean)"</span>:    np.mean((y_test <span class="op">-</span> mean_pred) <span class="op">**</span> <span class="dv">2</span>),</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>            <span class="st">"MAE (median)"</span>:  np.mean(np.<span class="bu">abs</span>(y_test <span class="op">-</span> median_pred))}</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>results <span class="op">=</span> {</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"No-X baseline"</span>: evaluate(y_train.mean(), np.median(y_train)),</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CPM"</span>:           evaluate(cpm_mean, cpm_median),</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Truth"</span>:         evaluate(true_mean, true_median),</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'model'</span><span class="sc">:&lt;16}</span><span class="ss">"</span> <span class="op">+</span> <span class="st">""</span>.join(<span class="ss">f"</span><span class="sc">{</span>k<span class="sc">:&gt;16}</span><span class="ss">"</span> <span class="cf">for</span> k <span class="kw">in</span> results[<span class="st">"CPM"</span>]))</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, r <span class="kw">in</span> results.items():</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>name<span class="sc">:&lt;16}</span><span class="ss">"</span> <span class="op">+</span> <span class="st">""</span>.join(<span class="ss">f"</span><span class="sc">{</span>v<span class="sc">:&gt;16.3f}</span><span class="ss">"</span> <span class="cf">for</span> v <span class="kw">in</span> r.values()))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>model                 MSE (mean)    MAE (median)
No-X baseline             20.432           2.679
CPM                       12.765           2.046
Truth                     13.135           2.041</code></pre>
</div>
</div>
<ul>
<li><strong>CPM vs.&nbsp;baseline:</strong> the CPM should have clearly lower error on all three measures. That is the value of using <span class="math inline">\(X\)</span>.</li>
<li><strong>CPM vs.&nbsp;truth:</strong> the gap should be small. The truth’s error is mostly irreducible noise (the random <span class="math inline">\(\epsilon\)</span>), so a CPM near the truth is doing about as well as possible.</li>
</ul>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-liu2017" class="csl-entry" role="listitem">
Liu, Qi, Bryan E. Shepherd, Chun Li, and Frank E. Harrell Jr. 2017. <span>“Modeling Continuous Response Variables Using Ordinal Regression.”</span> <em>Statistics in Medicine</em> 36 (27): 4316–35. https://doi.org/<a href="https://doi.org/10.1002/sim.7433">https://doi.org/10.1002/sim.7433</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./visualizing_model_molnar_2022.html" class="pagination-link" aria-label="Partial Dependence Plot (PDP)">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Partial Dependence Plot (PDP)</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./summary.html" class="pagination-link" aria-label="Summary">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Summary</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>